[advisories]
version = 2
ignore = []

[licenses]
confidence-threshold = 0.8
allow = ["MIT"]

[bans]
multiple-versions = "warn"
allow = []
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
